### PR TITLE
Fix bugs in KEEP token dashboard

### PR DESCRIPTION
**Pull request by r-czajkowski**
Closes: #1824 

This PR fixes a bunch of bugs from Antonio's notes. This PR:
* fixes fetching keep address from a `Deposit` contract. This bug was related to keep-network/tbtc@b0660f4,
* adds a temporary(because we don't have all on Figma yet) `Connect wallet` pages (Applications, Operations, Earnings page),
* fixes bug #1824,
* fixes overlapping tooltip content,
* adds loading feedback on the tBTC earning page,
* improves resource tooltip by setting a default link style instead of a link that looks like a button.

<details>
  <summary>Tooltip bug</summary>

### bug:
obraz

### fix:
obraz
</details>

<details>
  <summary>Bonding secion of tBTC</summary>

### bug:
obraz

### fix:
obraz

obraz

</details>

<details>
  <summary>Missing loading indicator in tBTC earnings page</summary>

obraz
</details>

<details>
  <summary>Improve resource tooltip:</summary>

obraz
</details>

### CODE REVIEW

**Comment by michalsmiarowski** [comment]
**Bonding section of tBTC**

`Available Eth` has scrollbar on the bottom which i don't see on your screenshots (both on Chrome and Firefox):
image

Is this the desired look?

**Comment by r-czajkowski** [comment]
> **Bonding section of tBTC**
> 
> `Available Eth` has scrollbar on the bottom which i don't see on your screenshots (both on Chrome and Firefox):
> image
> 
> Is this the desired look?

noope. On my Firefox the scrollbar is displayed only when scrolling and it looks much better than screenshot above 🤔 I'll dig into it

**Review by michalsmiarowski — CHANGES_REQUESTED** [review]
To me the code itself looks good 👍 The only thing to check is the bottom scrollbar issue at the available field which i mentioned in the PR comment earlier.

**Comment by Shadowfiend** [comment]
> On my Firefox the scrollbar is displayed only while scrolling

This is going to vary by system settings, amongst other things---and I would guess there will always be a scrollbar on non-macOS platforms. The way we've handled this elsewhere is to have a hover value that lets you see the full amount---we should be consistent about using that strategy everywhere IMO. Let's pick a precision (3-4 decimals seems reasonable), fix the width around that precision, and provide a hover that shows the full precision.

**Comment by Shadowfiend** [comment]
It may also make sense to lay out the buttons in this table as their own `td`, and make the `Available ETH` header cell a `colspan="2"`. That should help the browser avoid overlap even in cases where things don't go quite as planned.

**Comment by Shadowfiend** [comment]
Not a blocker, but other things I've noticed now that tBTC earnings is working:

- We round precision for the amount in the table, but no hover to show the full precision.
- The view in block explorer link links to Ropsten even if the dashboard is on mainnet.

**Review by Shadowfiend — APPROVED** [review]
Went through all of these, they look good overall. Flagged a couple of extra things I've noticed, none blocking or urgent. Let's roll it in.

**Comment by r-czajkowski** [comment]
> The view in block explorer link links to Ropsten even if the dashboard is on mainnet.

If you run the dapp with `npm start`, it works in the development environment. In the development env, the dapp returns default chain ID otherwise gets chain id from `keep-network/*` artifacts. Pls [see](https://github.com/keep-network/keep-core/blob/master/solidity/dashboard/src/connectors/utils.js#L25-L32). I believe it works at dashboard.keep.network.

**Pull request merged**
