### PR TITLE
Disable menu on the wallet page

### PR DESCRIPTION
**Pull request by r-czajkowski**
Closes: #1777

obraz

### CODE REVIEW

**Comment by dimpar** [comment]
Disable functionality work, but I think it lacks of navigation link back to "Connect wallet". Before you connect a wallet, you can navigate to Glossary page. But then, there's no clear way to go back. You can click the logo or disabled menu, but it is sort of guessing?

**Comment by liz-shinn** [comment]
>But then, there's no clear way to go back. You can click the logo or disabled menu, but it is sort of guessing? @liz-shinn, @r-czajkowski thoughts?

Oooo good point. Hmm... is there still a notification in the top left to "connect a wallet" that links to that page? There was one in the design. I'm not sure that's enough of a visual cue, but could help.

connectwallet

**Comment by liz-shinn** [comment]
Screen Shot 2020-07-02 at 12 29 44 PM

I think adding this arrow could also help ^

**Comment by dimpar** [comment]
Created [issue](https://github.com/keep-network/keep-core/issues/1887) for clickable "select a wallet" message

**Pull request merged**
