### PR TITLE
Link to the tx

### PR DESCRIPTION
**Pull request by r-czajkowski**
Closes: #1769 

This PR adds the link to the transaction on the etherscan and updates styles of the message component.

transaction-is-pending

obraz

### CODE REVIEW

**Comment by dimpar** [comment]
Do you think we can keep an address showing for a bit longer?

too-fast2

**Comment by r-czajkowski** [comment]
I think this situation ^ is only possible with local chains like Ganache. In the 'real-world' it will be much longer.

**Comment by dimpar** [comment]
The other option would be adding the etherscan link in the success banner, and give a user control when he wants to close it. This way a user certainly won't miss the timeline for clicking the nav link.

**Comment by r-czajkowski** [comment]
Agree 👍 , but maybe let's open an issue for that. I think it may take a while.

**Comment by dimpar** [comment]
okay, I've created an issue for that: https://github.com/keep-network/keep-core/issues/1813

**Comment by liz-shinn** [comment]
+1 to including an option to close the success notification so it stays on screen longer, as well as adding a link to the success notification.

**Pull request merged**
