### PR TITLE
expose peers list as part of metrics

### PR DESCRIPTION
**Pull request by ElderOrb**
Refs https://github.com/keep-network/keep-core/issues/1930

depends on https://github.com/keep-network/keep-common/pull/42

### CODE REVIEW

**Comment by ElderOrb** [comment]
@pdyraga @mhluongo any thoughts on this & https://github.com/keep-network/keep-common/pull/42 ?

**Comment by pdyraga** [comment]
Thanks for this @ElderOrb, I'll try to get my eyes on it this week or early next week.

**Comment by lukasz-zimnoch** [comment]
@ElderOrb I left some thoughts here: https://github.com/keep-network/keep-common/pull/42#issuecomment-663483983

**Comment by pdyraga** [comment]
Closing it without merging after the discussion in https://github.com/keep-network/keep-common/pull/42#issuecomment-663483983. Thanks for the contribution @ElderOrb and excited for more! 🙌

**Pull request closed without merging**
