### PR TITLE
Add SECURITY.md with vulnerability disclosure policy

### PR DESCRIPTION
**Pull request by Shadowfiend**
This outlines both the versions that are supported for vulnerabilities at this
time, as well as the requested process for disclosing vulnerabilities to the
team.

Goes hand-in-hand with keep-network/website#325.

### CODE REVIEW

**Review by mhluongo — CHANGES_REQUESTED** [review]
We're pushing Keybase in the security.txt, but don't mention it here and prefer encrypted email.. let's be consistent

**Comment by Shadowfiend** [comment]
Great point, will flag Keybase as our preferred real-time mechanism for now.

**Comment by Shadowfiend** [comment]
Great point, will flag Keybase as our preferred real-time mechanism for now. Note that point of first contact is still going to be encrypted email, and will remain our preferred approach for actual comms, since it allows a single address to lead to a potentially-changing set of responsible parties on the back end---something we can't do well and confidentially on any real-time platform. Note also that security.txt points to security@ as the point of contact, and uses Keybase solely as a PGP key lookup strategy.

**Comment by Shadowfiend** [comment]
Updated and marked ready for review.

**Review by mhluongo — APPROVED** [review]
🎇

**Pull request merged**
