### PR TITLE
Metamask pop up

### PR DESCRIPTION
**Pull request by r-czajkowski**
Closes: #1956

This PR improves UX while connecting with wallet. Here we added loading indicators when the dapp fetches the wallet addresses and connects with a wallet. We also display the `install metamask` button only in case the user does not have the extension installed.

<details>
  <summary>Screenshoots</summary>

no MetaMask ext:
no-metamask-ext

wrong netowork error:
mm-wrong-net

mm connecting:
mm-connecting

ledger loading wallet addresses:
ledger-loading-addresses

ledger select address:
ledger-select-address

trezor loading wallet addresses:
obraz

trezor select address:
trezor-select-acc

</details>

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Let's make sure to include some context in the PR description as well (though it can delegate to the issue for full detail).

**Comment by r-czajkowski** [comment]
> Let's make sure to include some context in the PR description as well (though it can delegate to the issue for full detail).

ah yeah.... forgot about issue description 🤦, sorry...

**Comment by Shadowfiend** [comment]
This fixes a bunch of bits around the wallet UX, awesome work! Going to do a deeper review and take it for a test drive… Hopefully today.

**Review by Shadowfiend — APPROVED** [review]
Screen Shot 2020-09-25 at 18 30 09

Small note: there's a breakpoint where this is what I see in Firefox ^^. It happens to apply to the range of sizes I typically keep my browser windows at 🙉 

The improvements here are huge though, nice work! :rocket:

**Pull request merged**
