### PR TITLE
daramir/fix 20201013 report displaytext

### PR DESCRIPTION
**Pull request by daramir**
Adjusting the text displayed for one of the links to the report to match the right deposit size (0.01 BTC instead of 0.1 BTC)

### CODE REVIEW

**Comment by pdyraga** [comment]
Thanks for that @daramir. Some git rebase will be needed here to get rid of merge commits from the history.

**Review by Shadowfiend — APPROVED** [review]
Only an order of magnitude difference :grimacing:

**Comment by Shadowfiend** [comment]
Let me see if I can massage this guy into behaving.

**Comment by Shadowfiend** [comment]
Closing in favor of #2134.

**Pull request closed without merging**
