### PR TITLE
Wallet page bug fixes

### PR DESCRIPTION
**Pull request by r-czajkowski**
Closes: #1780
Closes: #1779

This PR:
* disables the `Coinbase` option, because we do not yet support `Coinbase`,
* fixes a bug related to freezing the dapp when Metamask modal is opened but closed w/o selection.

### CODE REVIEW

**Comment by pdyraga** [comment]
@r-czajkowski Let's summarize in the PR description what are the bugs we are fixing, we can even quote the referenced issues.

**Comment by dimpar** [comment]
Coinbase wallet is disabled, but if you click on it, the popup will show up.
Screenshot 2020-07-06 at 11 48 10

**Comment by dimpar** [comment]
Tested issues with MetaMask modal and coinbase selection. Looks good.

**Comment by liz-shinn** [comment]
Nice! Lookin' good. For the coinbase issue - how did we end up resolving that? Did we show it in the disabled state?

**Comment by r-czajkowski** [comment]
@liz-shinn, I've added a screenshot to PR description. We show the Conibase wallet card in a disabled state and the user is not able to open a Coinbase popup.

**Comment by liz-shinn** [comment]
Thanks @r-czajkowski ! Looks good.

**Pull request merged**
