### PR TITLE
CODEOWNERS for smart contracts

### PR DESCRIPTION
**Pull request by pdyraga**
Setting @Shadowfiend and @pdyraga as code owners for `keep-core` smart contracts deployed to mainnet in 1.0.1 release.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
My thought was we would only be CODEOWNERS on the contracts that are deployed, rather than on all of them :grimacing:

**Comment by pdyraga** [comment]
I am hoping to freeze them tomorrow 

> My thought was we would only be CODEOWNERS on the contracts that are deployed, rather than on all of them 😬

Updated in 6fb7538. Side note, I realized only 4 contracts are not locked/not deployed yet. 😆

**Comment by Shadowfiend** [comment]
Two things:
- Let's make sure we've hit all libraries as well.
- Let's add package.json, since dependencies live in there.

**Comment by pdyraga** [comment]
Ready for another chance!

**Pull request merged**
